### ISSUE TITLE
About the results in Table 4

### ISSUE THREAD

**Issue by hyunOO** [VITA-Group/SDCLR#2]
Hello, @geekJZY, thanks for sharing your great work!
I have a question about (1) how _Std_ is computed, and (2) the results in Table 4.

![스크린샷 2021-09-07 오후 3 43 00](https://user-images.githubusercontent.com/28649549/132296832-32da2c39-aa96-4124-9848-773713864d8d.png)

For the result on CIFAR10-LT, baseline seems more balanced values than SDCLR.

The second row of Table 4 shows the accuracy of [Many, Medium, Few] of the model which is trained on CIFAR10-LT.
SimCLR: [78.18 ± 4.18, 76.23 ± 5.33, 71.37 ± 7.07]
SDCLR:  [86.44 ± 3.12, 81.84 ± 4.78, 76.23 ± 6.29]
The accuracy gap between Many and Few of SImCLR is under 7% but SDCLR is over 10%.

But Table 4 says SDCLR has lower _Std_ than SimCLR. How did you compute the metric?
Thanks!

**Comment by geekJZY** [comment]
The _Std_ is the standard deviation of _Many_, _Medium_, and _Few_. Specifically, we use NumPy.std() for calculation.

**Comment by geekJZY** [comment]
Thanks for your interest. To further answer your question. Here we illustrate the results on each split for a better view (Results are reproduced after submitting, which  differs a little from reported):

Results of SimCLR for 5 splits on CIFAR10 :
| split count | _Many_        | _Medium_      | _Few_         | _Std_        | All         |
|-----------|-------------|-------------|-------------|------------|-------------|
| 1         | 84.28       | 71.50       | 67.13       | 7.27       | 75.30       |
| 2         | 71.45       | 74.13       | 79.07       | 3.15       | 74.54       |
| 3         | 76.13       | 75.60       | 76.1        | 0.24       | 75.96       |
| 4         | 79.00        | 86.80       | 57.87       | 12.22      | 75.00       |
| 5         | 79.75       | 72.16       | 75.77       | 3.10       | 76.28       |
| Ave       | 78.12+-4.24 | 76.04+-5.57 | 71.19+-7.76 | 5.20+-4.17 | 75.42+-0.63 |

Results of SDCLR for 5 splits on CIFAR10:
| split count | _Many_        | _Medium_      | _Few_         | _Std_        | All         |
|-----------|-------------|-------------|-------------|------------|-------------|
| 1         |  90.15      |    77.97    |   73.53     |   7.03     |  81.51      |
| 2         |    81.1    |    81.00    |   81.67     |   0.29     |      81.24  |
| 3         |    85.13    |    79.17   |   81.10       |    2.48    |     82.13   |
| 4         |    87.55     |   91.2     |    65.07    |  11.56     |   81.90     |
| 5         |    88.25    |   79.87     |   79.80     |    3.97    |    83.20    |
| Ave       | 86.44+-3.12  | 81.84+-4.78 | 76.23+-6.29 | 5.06+-3.91 | 82.00+-0.68 |

Here we also offer more discussions about these two tables.
**Why the Many is not always higher than Medium or Few in some splits**
As discussed in 3.3 of our paper, besides the imbalanced dataset, there also exists multi-label attribute imbalance. Since CIFAR10 only contains 10 classes, there are only 3-4 classes for Many, Medium, and Few. Therefore the accuracy of Many, Medium and Few could be heavily affected by the multi-label attribute imbalance. 

**Why average Std is better while the gap between Many and Few is larger**
As illustrated in the Table, the proposed SDCLR successfully mitigates the multi-label attribute imbalance problem on most splits, which brings an overall improvement on Std.

**Comment by hyunOO** [comment]
Thanks for the replies!
I have one more question.
I wonder what is "5 splits on CIFAR-10". Does it mean the "5 random seed trials on CIFAR-10"?

**Comment by geekJZY** [comment]
5 splits mean five different imbalanced subsets of CIFAR10. You can find the sets here: https://github.com/VITA-Group/SDCLR/tree/main/split/cifar10_imbSub_with_subsets.

**Comment by hyunOO** [comment]
Thank you so much :)
